- hosts: test
  become: yes

  tasks:

  - name: Copy alert.rules.yml
    copy:
      src: /home/ansible/alert.rules.yml
      dest: /etc/prometheus/alert.rules.yml
      owner: prometheus
      group: prometheus
      mode: 0755
    notify:
      - Copy alert.rules.yml

  handlers:
  - name: Copy alert.rules.yml
    service:
      name: prometheus
      state: restarted

