apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-k8s
data:
  prometheus.yml: |
    global:
        scrape_interval: 30s
        scrape_timeout: 30s
    scrape_configs:
      - job_name: prometheus_metrics
        static_configs:
          - targets:
            - prometheus:9090
            labels:
              contur: openshift